### PR TITLE
Timesync Widget

### LINKED ISSUE #31: Timesync widget
Please make a widget for timesync that cycles through the following displays:
- A list of users, limited to ten, sorted by hours billed over the last week.
- A pie chart for all billed hours over the last week, with wedges for each project.
- A line chart of total billed hours per day over the last week.

The code should be modular enough that changing from "the last week" to "the last month" should be a one-liner in a configuration file.

Once this widget is done, we can identify changes or improvements -- but first, we need something to change or improve!

### PR DESCRIPTION
**Pull request by MaraJade**
Fixes #31  
## Changes in this PR.

- [X] Adds TimeSync widget to OSL dashboard
## Testing this PR.

1. Set up Fenestra
2. Copy config.yml.sample to config.yml and fill in the timesync settings
3. Run `dashing start`
4. Navigate to 0.0.0.0:3030 in your browser

@osuosl/devs

### CODE REVIEW

**Comment by Kennric** [comment]
Looks good! +1

**Comment by tschuy** [comment]
Comments from the peanut gallery: perhaps you could display the number of people that worked on a certain day, or total time worked?

(apologies for just commenting with little context)

**Comment by MaraJade** [comment]
Those would be future feature requests. Right now we're just trying to get this working and merged in

**Comment by ElijahCaine** [comment]
@MaraJade I spent a while getting this setup (non-trivial) and I can't get it working. All of the dependencies install just fine after some trial/error/googling, but I can't get the app to actually run.

I'd really appreciate it if you tried getting this installed from the ground up using docker:
```
On your workstation:
$ docker run -it -p 3030:3030 debian:latest /bin/bash

In the container
root@ab7cfa91a61c:/opt# git clone https://github.com/osuosl/fenestra.git /opt/code
root@ab7cfa91a61c:/opt# cd /opt/code
root@ab7cfa91a61c:/opt/code# git checkout issues/31/timesync_widget
...
# install dependencies
# install correct version of ruby
# get the app running
# record all steps necessary to do this and post them in this PR.
```

We can then use your list of exact steps to update the README with a more thorough install guide.

**Comment by Kennric** [comment]
@aaroncohen73 can you take a look at this?

**Comment by Kennric** [comment]
@LyonesGamer please take a look at this

**Comment by Kennric** [comment]
Looks good to me +1

**Pull request merged**
